export {
  changeUserInput,
  checkLevel,
  checkSolution,
  clearUserInput,
  finishGame,
  finishSession,
  generateDigits,
  getTotal,
  handleScore,
  mathActions,
  recordGame,
  recordSession,
  removeUserInput,
  resetSession,
  setOperation,
  startGame,
} from './math.actions';
